version: "3"
services:
  db:
    container_name: mssql
    image:  mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "1433:1433"
    environment:
      DATABASE_URL: "mssql+pyodbc://localhost/FastApi?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes&timezone=UTC;"
    volumes:
      - mssql-data:/var/opt/mssql
  api:
    build: .
    ports: 
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./.env